Repository hapostgres/pg_auto_failover, pull requests merged in 2019-11, with the labels that each got.

#97 Review main loop chatter, make it less verbose by default.
  src/bin/pg_autoctl/loop.c
Labels: bug, enhancement

#85 Minor spelling, grammar, and wordsmithing
  docs/fault-tolerance.rst
Labels: bug, docs

#100 Improve options and arguments parsing.
  src/bin/lib/subcommands.c/commandline.c
  src/bin/pg_autoctl/cli_common.c
  src/bin/pg_autoctl/cli_common.h
  src/bin/pg_autoctl/cli_create_drop_node.c
  src/bin/pg_autoctl/cli_do_root.c
  src/bin/pg_autoctl/cli_enable_disable.c
  src/bin/pg_autoctl/cli_formation.c
  src/bin/pg_autoctl/cli_root.c
  src/bin/pg_autoctl/cli_root.h
  src/bin/pg_autoctl/cli_service.c
  src/bin/pg_autoctl/cli_show.c
  src/bin/pg_autoctl/cli_systemd.c
  src/bin/pg_autoctl/main.c
Labels: bug
