Repository hapostgres/pg_auto_failover, pull requests merged in 2020-09, with the labels that each got.

#346 Multiple Standby Documentation
  .gitignore
  CONTRIBUTING.md
  Makefile
  README.md
  docs/.gitignore
  docs/architecture-multi-standby.rst
  docs/architecture.rst
  docs/conf.py
  docs/failover-state-machine.rst
  docs/faq.rst
  docs/fault-tolerance.rst
  docs/how-to.rst
  docs/index.rst
  docs/intro.rst
  docs/ref/reference.rst
  docs/tikz/Makefile
  docs/tikz/arch-multi-standby.svg
  docs/tikz/arch-multi-standby.tex
  docs/tikz/arch-single-standby.svg
  docs/tikz/arch-single-standby.tex
  docs/tikz/arch-three-standby-one-async.svg
  docs/tikz/arch-three-standby-one-async.tex
  docs/tikz/arch-three-standby.svg
  docs/tikz/arch-three-standby.tex
  docs/tikz/fsm.svg
  docs/tikz/fsm.tex
  docs/tutorial.rst
  src/bin/pg_autoctl/monitor.c
  src/bin/pg_autoctl/nodestate_utils.c
  src/monitor/pgautofailover.sql
Labels: docs

#388 Fix/tuning and recovery setup
  src/bin/pg_autoctl/pgctl.c
  src/bin/pg_autoctl/pgtuning.c
  tests/pgautofailover_utils.py
Labels: bug

#390 Various improvements to the LaTeX diagrams
  .editorconfig
  CONTRIBUTING.md
  docs/tikz/Makefile
  docs/tikz/arch-multi-standby.svg
  docs/tikz/arch-multi-standby.tex
  docs/tikz/arch-single-standby.svg
  docs/tikz/arch-single-standby.tex
  docs/tikz/arch-three-standby-one-async.svg
  docs/tikz/arch-three-standby-one-async.tex
  docs/tikz/arch-three-standby.svg
  docs/tikz/arch-three-standby.tex
  docs/tikz/fsm.tex
Labels: docs

#391 Remove split rectangle from single standby diagram
  docs/tikz/arch-single-standby.svg
  docs/tikz/arch-single-standby.tex
Labels: docs

#394 Improve monitor listener main loop.
  src/bin/pg_autoctl/cli_do_monitor.c
  src/bin/pg_autoctl/defaults.h
  src/bin/pg_autoctl/monitor.c
  src/bin/pg_autoctl/monitor.h
  src/bin/pg_autoctl/nodestate_utils.c
  src/bin/pg_autoctl/nodestate_utils.h
  src/bin/pg_autoctl/pgsql.c
  src/bin/pg_autoctl/pgsql.h
  src/bin/pg_autoctl/service_monitor.c
  src/bin/pg_autoctl/signals.c
  src/bin/pg_autoctl/signals.h
Labels: bug, user experience

#397 Fix a corner case which leaves a node in JOIN_PRIMARY state.
  src/bin/pg_autoctl/fsm_transition.c
  src/monitor/group_state_machine.c
  src/monitor/node_active_protocol.c
Labels: bug

#396 Implement proper signal handling in select calls.
  src/bin/pg_autoctl/monitor.c
Labels: user experience

#395 Allow registering multiple standbys concurrently
  src/bin/pg_autoctl/fsm_transition.c
  src/bin/pg_autoctl/keeper.c
  src/bin/pg_autoctl/keeper.h
  src/bin/pg_autoctl/keeper_pg_init.c
  src/bin/pg_autoctl/pgsql.c
  src/bin/pg_autoctl/pgsql.h
  src/bin/pg_autoctl/primary_standby.c
  src/bin/pg_autoctl/primary_standby.h
  src/monitor/node_active_protocol.c
  tests/test_multi_maintenance.py
Labels: bug

#403 Fix/test primary conninfo
  src/bin/pg_autoctl/cli_do_misc.c
  src/bin/pg_autoctl/cli_do_root.c
  src/bin/pg_autoctl/cli_do_root.h
  src/bin/pg_autoctl/pgctl.c
  src/bin/pg_autoctl/pgctl.h
  src/bin/pg_autoctl/pgsql.c
  src/bin/pg_autoctl/pgsql.h
Labels: bug

#398 Add some targets to quickly spawn a cluster
  .gitignore
  Makefile
  src/bin/pg_autoctl/cli_do_misc.c
  src/bin/pg_autoctl/cli_do_root.c
  src/bin/pg_autoctl/cli_do_root.h
  src/bin/pg_autoctl/cli_do_tmux.c
Labels: user experience

#402 When secondary, don't ensure current state before a transition.
  src/bin/pg_autoctl/keeper.c
  src/bin/pg_autoctl/primary_standby.c
Labels: bug

#359 Implement a retry policy for deadlocks and other transient failures.
  src/bin/pg_autoctl/cli_enable_disable.c
  src/bin/pg_autoctl/keeper.c
  src/bin/pg_autoctl/monitor.c
  src/bin/pg_autoctl/monitor.h
  src/bin/pg_autoctl/pgsetup.c
  src/bin/pg_autoctl/pgsql.c
  src/bin/pg_autoctl/pgsql.h
  src/bin/pg_autoctl/service_keeper.c
Labels: user experience

#410 Refrain from validating primary conninfo when we don't have a primary.
  src/bin/pg_autoctl/primary_standby.c
Labels: bug

#405 Adjust formation->number_sync_standbys when dropping a node.
  src/monitor/node_active_protocol.c
  src/monitor/pgautofailover.sql
Labels: bug

#406 Fix network partition detections.
  src/bin/pg_autoctl/service_keeper.c
  tests/pgautofailover_utils.py
  tests/test_basic_operation.py
Labels: bug

#409 Feature/tmux session
  Makefile
  src/bin/lib/subcommands.c/runprogram.h
  src/bin/pg_autoctl/cli_do_root.c
  src/bin/pg_autoctl/cli_do_root.h
  src/bin/pg_autoctl/cli_do_tmux.c
  src/bin/pg_autoctl/config.c
Labels: user experience

#414 Fix taking control of an already running Postgres instance.
  src/bin/pg_autoctl/pgsetup.c
Labels: bug

#417 Ensure we set PG_AUTOCTL_DEBUG before calling pg_autoctl do commands.
  src/bin/pg_autoctl/cli_do_tmux.c
Labels: bug

#419 Update documentation with pg_autoctl do tmux ... commands.
  docs/ref/reference.rst
Labels: docs

#425 Update tutorial for release 1.4.0.
  docs/fsm.png
  docs/tutorial.rst
Labels: docs
