Repository hapostgres/pg_auto_failover, pull requests merged in 2020-08, with the labels that each got.

#340 Implement a node name.
  src/bin/pg_autoctl/cli_common.c
  src/bin/pg_autoctl/cli_common.h
  src/bin/pg_autoctl/cli_create_drop_node.c
  src/bin/pg_autoctl/cli_do_monitor.c
  src/bin/pg_autoctl/cli_enable_disable.c
  src/bin/pg_autoctl/cli_get_set_properties.c
  src/bin/pg_autoctl/cli_service.c
  src/bin/pg_autoctl/fsm.c
  src/bin/pg_autoctl/keeper.c
  src/bin/pg_autoctl/keeper.h
  src/bin/pg_autoctl/keeper_config.c
  src/bin/pg_autoctl/keeper_config.h
  src/bin/pg_autoctl/keeper_pg_init.c
  src/bin/pg_autoctl/monitor.c
  src/bin/pg_autoctl/monitor.h
  src/bin/pg_autoctl/pgsetup.c
  src/bin/pg_autoctl/pgsql.h
  src/bin/pg_autoctl/service_keeper.c
  src/monitor/expected/monitor.out
  src/monitor/formation_metadata.c
  src/monitor/group_state_machine.c
  src/monitor/node_active_protocol.c
  src/monitor/node_metadata.c
  src/monitor/node_metadata.h
  src/monitor/notifications.c
  src/monitor/notifications.h
  src/monitor/pgautofailover.sql
  src/monitor/sql/monitor.sql
  tests/pgautofailover_utils.py
  tests/test_basic_operation.py
Labels: user experience

#349 Exit early with EXIT_CODE_QUIT in pg_autoctl create when possible.
  src/bin/pg_autoctl/keeper_pg_init.c
Labels: user experience

#355 Prevent pg_autoctl create to do anything if pg_autoctl is running.
  src/bin/pg_autoctl/cli_create_drop_node.c
Labels: bug, user experience

#342 Refrain from useless verifications of pg_controldata properties.
  src/bin/pg_autoctl/keeper.c
  src/bin/pg_autoctl/pgsetup.c
  src/bin/pg_autoctl/pgsetup.h
Labels: bug

#357 In some cases, we still need to call pg_controldata.
  src/bin/pg_autoctl/keeper.c
Labels: bug

#358 Fix dropping the old-primary node.
  src/monitor/node_active_protocol.c
  tests/test_multi_standbys.py
Labels: bug

#335 Feature/pgtune
  src/bin/pg_autoctl/cli_do_misc.c
  src/bin/pg_autoctl/cli_do_root.c
  src/bin/pg_autoctl/cli_do_root.h
  src/bin/pg_autoctl/keeper_pg_init.c
  src/bin/pg_autoctl/pgctl.c
  src/bin/pg_autoctl/pgtuning.c
  src/bin/pg_autoctl/pgtuning.h
  src/bin/pg_autoctl/primary_standby.c
  src/bin/pg_autoctl/system_utils.c
  src/bin/pg_autoctl/system_utils.h
Labels: user experience

#360 Fix pg_autoctl status when pg_autoctl is not running.
  src/bin/pg_autoctl/cli_service.c
  src/bin/pg_autoctl/cli_show.c
  src/bin/pg_autoctl/pidfile.c
  src/bin/pg_autoctl/pidfile.h
Labels: bug

#361 Fix/fatal auth pgautofailover monitor
  src/bin/pg_autoctl/cli_do_misc.c
  src/bin/pg_autoctl/cli_do_root.c
  src/bin/pg_autoctl/cli_do_root.h
  src/bin/pg_autoctl/defaults.h
  src/bin/pg_autoctl/fsm_transition.c
  src/bin/pg_autoctl/keeper_pg_init.c
  src/bin/pg_autoctl/monitor_pg_init.c
  src/bin/pg_autoctl/pgsql.c
  src/bin/pg_autoctl/pgsql.h
  src/bin/pg_autoctl/primary_standby.c
  src/bin/pg_autoctl/primary_standby.h
  src/monitor/health_check_worker.c
  tests/test_auth.py
  tests/test_create_run.py
Labels: user experience

#367 Don't change the replication slot name at reload.
  src/bin/pg_autoctl/keeper_config.c
Labels: bug

#370 Fix when to allow for a failover in multiple standbys.
  src/monitor/node_active_protocol.c
  src/monitor/node_metadata.c
Labels: bug

#336 Cleanup/show state
  src/bin/pg_autoctl/cli_common.c
  src/bin/pg_autoctl/cli_common.h
  src/bin/pg_autoctl/cli_do_misc.c
  src/bin/pg_autoctl/cli_do_monitor.c
  src/bin/pg_autoctl/cli_enable_disable.c
  src/bin/pg_autoctl/cli_perform.c
  src/bin/pg_autoctl/cli_root.c
  src/bin/pg_autoctl/cli_show.c
  src/bin/pg_autoctl/monitor.c
  src/bin/pg_autoctl/monitor.h
  src/bin/pg_autoctl/nodestate_utils.c
  src/bin/pg_autoctl/nodestate_utils.h
  src/bin/pg_autoctl/parsing.c
  src/bin/pg_autoctl/parsing.h
  src/bin/pg_autoctl/pgsetup.c
  src/bin/pg_autoctl/pgsetup.h
  src/bin/pg_autoctl/pgsql.h
  src/bin/pg_autoctl/state.h
  src/monitor/health_check.h
  src/monitor/health_check_metadata.c
  src/monitor/notifications.c
  src/monitor/pgautofailover.sql
  tests/pgautofailover_utils.py
Labels: user experience

#368 Fix tutorial typos, and make sure all code blocks are displayed
  docs/tutorial.rst
Labels: docs

#366 Fix/number sync standby new async standby
  src/monitor/formation_metadata.c
  src/monitor/node_active_protocol.c
  src/monitor/node_metadata.c
  src/monitor/node_metadata.h
  tests/pgautofailover_utils.py
  tests/test_multi_async.py
Labels: bug

#373 Reduce chatter when postmaster.pid is read empty.
  src/bin/pg_autoctl/pgsetup.c
Labels: user experience

#372 Improve testing for pre-existing Postgres directory in monitor init.
  src/bin/pg_autoctl/monitor_pg_init.c
  tests/test_multi_async.py
Labels: bug

#374 Feature/default node names for citus formations
  src/monitor/Makefile
  src/monitor/expected/monitor.out
  src/monitor/expected/workers.out
  src/monitor/formation_metadata.h
  src/monitor/node_active_protocol.c
  src/monitor/node_metadata.c
  src/monitor/node_metadata.h
  src/monitor/pgautofailover.sql
  src/monitor/sql/monitor.sql
  src/monitor/sql/workers.sql
Labels: enhancement

#376 Implement pg_autoctl perform promotion.
  src/bin/pg_autoctl/cli_common.c
  src/bin/pg_autoctl/cli_common.h
  src/bin/pg_autoctl/cli_get_set_properties.c
  src/bin/pg_autoctl/cli_perform.c
  src/bin/pg_autoctl/monitor.c
  src/bin/pg_autoctl/monitor.h
  src/monitor/group_state_machine.c
  src/monitor/node_active_protocol.c
  src/monitor/node_metadata.h
  src/monitor/pgautofailover.sql
  tests/pgautofailover_utils.py
  tests/test_basic_operation.py
  tests/test_multi_async.py
Labels: user experience

#375 Fix/config set name
  src/bin/pg_autoctl/cli_config.c
  src/bin/pg_autoctl/ini_file.c
  src/bin/pg_autoctl/keeper.c
  src/bin/pg_autoctl/keeper.h
  src/bin/pg_autoctl/keeper_config.c
  src/bin/pg_autoctl/keeper_config.h
  src/bin/pg_autoctl/service_keeper.c
  tests/test_basic_operation.py
Labels: user experience

#380 Fix unhealthy node detection when reported by pg_autoctl.
  src/monitor/group_state_machine.c
  tests/pgautofailover_utils.py
  tests/test_ensure.py
Labels: bug
