Repository hapostgres/pg_auto_failover, pull requests merged in 2020-06, with the labels that each got.

#279 When using --json output empty arrays rather than a blank line.
  src/bin/pg_autoctl/monitor.c
Labels: bug

#289 Improve pg_autoctl perform failover/switchover default --group.
  src/bin/pg_autoctl/cli_perform.c
  src/bin/pg_autoctl/monitor.c
  src/bin/pg_autoctl/monitor.h
Labels: bug

#288 Fix pgautofailover extension upgrade script from 1.2 to 1.3.
  src/monitor/pgautofailover--1.2--1.3.sql
Labels: bug

#291 Improve defaults for pg_autoctl perform failover/switchover.
  src/bin/pg_autoctl/cli_perform.c
Labels: bug

#299 Let the user know we are active doing PQPing attempts.
  src/bin/pg_autoctl/pgsql.c
Labels: bug

#287 doc: minor fixes to spelling and formatting
  CHANGELOG.md
  README.md
  docs/architecture.rst
  docs/fault-tolerance.rst
  docs/fsm/node-state-machine
  docs/operations.rst
  docs/ref/configuration.rst
  docs/ref/reference.rst
Labels: docs

#298 Skip network DNS probes on pg_autoctl create monitor --skip-pg-hba.
  src/bin/pg_autoctl/pghba.c
Labels: bug

#305 Don't show postgres startup messages on succesful startup
  src/bin/pg_autoctl/service_postgres.c
Labels: user experience

#294 Tighten when to accept to perform a failover even more.
  src/bin/pg_autoctl/fsm.c
  src/bin/pg_autoctl/fsm_transition.c
  src/bin/pg_autoctl/pgsql.c
  src/bin/pg_autoctl/pgsql.h
  src/bin/pg_autoctl/primary_standby.c
  src/bin/pg_autoctl/primary_standby.h
  src/monitor/node_active_protocol.c
  tests/test_auth.py
Labels: bug
