Repository hapostgres/pg_auto_failover, pull requests merged in 2020-11, with the labels that each got.

#488 Fix when we switch synchronous_standby_names to '*'.
  src/monitor/node_active_protocol.c
  tests/test_auth.py
  tests/test_basic_operation.py
Labels: bug

#479 Fix/hostname discovery
  src/bin/pg_autoctl/cli_common.h
  src/bin/pg_autoctl/cli_create_drop_node.c
  src/bin/pg_autoctl/cli_do_show.c
  src/bin/pg_autoctl/ipaddr.c
  src/bin/pg_autoctl/ipaddr.h
Labels: bug

#489 Fix/non default formation
  src/bin/pg_autoctl/cli_common.c
  src/bin/pg_autoctl/cli_common.h
  src/bin/pg_autoctl/cli_perform.c
  src/bin/pg_autoctl/cli_show.c
  tests/test_auth.py
Labels: bug

#486 Miscellaneous fixes for --disable-monitor mode
  src/bin/pg_autoctl/cli_common.c
  src/bin/pg_autoctl/cli_do_fsm.c
  src/bin/pg_autoctl/fsm_transition.c
Labels: enhancement

#496 Fix bug in monitor hostname discovery
  src/bin/pg_autoctl/cli_common.h
  src/bin/pg_autoctl/cli_create_drop_node.c
Labels: bug

#498 Fix error code path in pgsql clear_results.
  src/bin/pg_autoctl/pgsql.c
Labels: bug

#499 Fix race conditions in multiple-standby Group FSM for failover.
  src/bin/pg_autoctl/fsm.c
  src/monitor/group_state_machine.c
  tests/test_multi_ifdown.py
  tests/test_multi_maintenance.py
Labels: bug

#502 Fix synchronous_standby_names when disabling maintenance.
  .travis.yml
  src/monitor/group_state_machine.c
  src/monitor/node_metadata.c
  tests/pgautofailover_utils.py
  tests/test_basic_operation.py
  tests/test_multi_ifdown.py
  tests/test_multi_maintenance.py
Labels: bug

#504 Fix/debian stats temp directory
  Dockerfile
  src/bin/pg_autoctl/debian.c
Labels: bug

#494 Fix --disable-monitor to work with the parenting of Postgres model.
  Makefile
  src/bin/pg_autoctl/cli_common.c
  src/bin/pg_autoctl/cli_common.h
  src/bin/pg_autoctl/cli_create_drop_node.c
  src/bin/pg_autoctl/cli_do_fsm.c
  src/bin/pg_autoctl/cli_service.c
  src/bin/pg_autoctl/config.c
  src/bin/pg_autoctl/config.h
  src/bin/pg_autoctl/defaults.h
  src/bin/pg_autoctl/fsm_transition.c
  src/bin/pg_autoctl/keeper.c
  src/bin/pg_autoctl/keeper.h
  src/bin/pg_autoctl/keeper_config.c
  src/bin/pg_autoctl/keeper_config.h
  src/bin/pg_autoctl/keeper_pg_init.c
  src/bin/pg_autoctl/monitor.c
  src/bin/pg_autoctl/monitor.h
  src/bin/pg_autoctl/nodestate_utils.c
  src/bin/pg_autoctl/nodestate_utils.h
  src/bin/pg_autoctl/parsing.c
  src/bin/pg_autoctl/parsing.h
  src/bin/pg_autoctl/primary_standby.c
  src/bin/pg_autoctl/service_keeper.c
  src/bin/pg_autoctl/state.c
  tests/pgautofailover_utils.py
  tests/test_monitor_disabled.py
  tests/test_multi_standbys.py
Labels: bug

#513 Improve multi groups ordering in pg_autoctl show state.
  src/bin/pg_autoctl/monitor.c
Labels: enhancement, user experience

#510 Use PG_CONFIG has a hint to choose one of multiple Postgres versions.
  src/bin/pg_autoctl/cli_common.c
  src/bin/pg_autoctl/pgctl.c
  src/bin/pg_autoctl/pgctl.h
  src/bin/pg_autoctl/pgsetup.c
  src/monitor/group_state_machine.c
Labels: enhancement

#426 Attempt to fix Travis tests flackyness.
  tests/pgautofailover_utils.py
  tests/ssl_cert_utils.py
  tests/test_enable_ssl.py
Labels: enhancement

#515 Use pg_config from the PATH when we can't find a pg_ctl.
  src/bin/pg_autoctl/cli_common.c
  src/bin/pg_autoctl/cli_do_misc.c
  src/bin/pg_autoctl/cli_do_root.c
  src/bin/pg_autoctl/cli_do_root.h
  src/bin/pg_autoctl/cli_do_tmux.c
  src/bin/pg_autoctl/file_utils.c
  src/bin/pg_autoctl/file_utils.h
  src/bin/pg_autoctl/pgctl.c
  src/bin/pg_autoctl/pgctl.h
  src/bin/pg_autoctl/pgsetup.c
Labels: enhancement, user experience

#519 Fix build for *BSD
  src/bin/pg_autoctl/lock_utils.c
Labels: enhancement

#518 Review our reload hooks mechanism to make it usable.
  src/bin/pg_autoctl/keeper.c
  src/bin/pg_autoctl/keeper.h
  src/bin/pg_autoctl/service_keeper.c
Labels: bug
