Repository hapostgres/pg_auto_failover, pull requests merged in 2020-02, with the labels that each got.

#154 Feature/application name
  src/bin/pg_autoctl/cli_common.h
  src/bin/pg_autoctl/cli_do_misc.c
  src/bin/pg_autoctl/cli_root.c
  src/bin/pg_autoctl/cli_show.c
  src/bin/pg_autoctl/defaults.h
  src/bin/pg_autoctl/fsm_transition.c
  src/bin/pg_autoctl/keeper.c
  src/bin/pg_autoctl/pgctl.c
  src/bin/pg_autoctl/pgctl.h
  src/bin/pg_autoctl/pgsql.c
  src/bin/pg_autoctl/pgsql.h
  src/bin/pg_autoctl/primary_standby.c
  tests/pgautofailover_utils.py
Labels: bug, enhancement

#156 Refrain from being verbose when discovering if Postgres is running.
  src/bin/pg_autoctl/pgsetup.c
Labels: bug

#157 Fix include line detection.
  src/bin/pg_autoctl/pgctl.c
Labels: bug

#144 Support debian ubuntu style clusters
  src/bin/pg_autoctl/config.c
  src/bin/pg_autoctl/config.h
  src/bin/pg_autoctl/debian.c
  src/bin/pg_autoctl/debian.h
  src/bin/pg_autoctl/file_utils.c
  src/bin/pg_autoctl/file_utils.h
  src/bin/pg_autoctl/keeper_pg_init.c
  tests/pgautofailover_utils.py
  tests/test_debian_clusters.py
Labels: bug, enhancement

#159 Fix printLastEvents by fixing the SQL projection.
  src/bin/pg_autoctl/monitor.c
Labels: bug

#169 Implement an option to skip editing of HBA rules by pg_autoctl
  .travis.yml
  docs/install.rst
  docs/operations.rst
  docs/quickstart.rst
  docs/ref/reference.rst
  src/bin/lib/log/src/log.h
  src/bin/pg_autoctl/cli_common.c
  src/bin/pg_autoctl/cli_config.c
  src/bin/pg_autoctl/cli_create_drop_node.c
  src/bin/pg_autoctl/defaults.h
  src/bin/pg_autoctl/ini_file.c
  src/bin/pg_autoctl/keeper_config.c
  src/bin/pg_autoctl/keeper_pg_init.c
  src/bin/pg_autoctl/parsing.c
  src/bin/pg_autoctl/pgctl.c
  src/bin/pg_autoctl/pghba.c
  src/bin/pg_autoctl/pgsetup.c
  src/bin/pg_autoctl/pgsetup.h
  src/bin/pg_autoctl/primary_standby.c
  tests/pgautofailover_utils.py
  tests/test_auth.py
  tests/test_skip_pg_hba.py
Labels: enhancement

#161 Avoid using stdin/stdout/stderr as variable names
  .travis.yml
  src/bin/lib/subcommands.c/runprogram.h
  src/bin/pg_autoctl/pgctl.c
Labels: bug
