Repository hapostgres/pg_auto_failover, pull requests merged in 2020-12, with the labels that each got.

#521 Fix unhealthy nodes processing when wait_primary.
  src/monitor/group_state_machine.c
  tests/pgautofailover_utils.py
  tests/test_basic_operation.py
  tests/test_multi_async.py
  tests/test_multi_ifdown.py
Labels: bug

#525 Reduce tests chatter.
  tests/pgautofailover_utils.py
Labels: enhancement

#532 Improve our tmux integration for QA and testing.
  Makefile
  src/bin/pg_autoctl/cli_do_root.c
  src/bin/pg_autoctl/cli_do_tmux.c
  src/bin/pg_autoctl/cli_do_tmux.h
Labels: enhancement

#533 Fix FSM when a non-candidate node is back online.
  src/monitor/group_state_machine.c
  tests/pgautofailover_utils.py
  tests/test_basic_operation.py
  tests/test_multi_async.py
Labels: bug

#534 Fix assigning catchingup to unhealthy secondaries.
  src/monitor/group_state_machine.c
  tests/test_multi_async.py
Labels: bug

#536 Fix pg_autoctl set formation number-sync-standbys log output.
  src/bin/pg_autoctl/cli_get_set_properties.c
  src/bin/pg_autoctl/cli_show.c
  tests/pgautofailover_utils.py
Labels: bug, user experience

#537 Fully specify ordering of pg_autoctl get formation settings.
  src/bin/pg_autoctl/monitor.c
Labels: user experience

#546 Actually run black in CI
  .travis.yml
Labels: Developer productivity, Packaging and CI, Size: S, enhancement

#544 Implement pg_autoctl do azure commands.
  Makefile
  src/bin/pg_autoctl/azure.c
  src/bin/pg_autoctl/azure.h
  src/bin/pg_autoctl/azure_config.c
  src/bin/pg_autoctl/azure_config.h
  src/bin/pg_autoctl/cli_do_azure.c
  src/bin/pg_autoctl/cli_do_root.c
  src/bin/pg_autoctl/cli_do_root.h
  src/bin/pg_autoctl/cli_do_tmux.c
  src/bin/pg_autoctl/cli_do_tmux.h
  src/bin/pg_autoctl/cli_do_tmux_azure.c
Labels: Developer productivity, Size: XL, enhancement, user experience

#547 Deduplicate PATH entries that are symlinks resolving to other PATH entries
  src/bin/pg_autoctl/file_utils.c
  src/bin/pg_autoctl/file_utils.h
  src/bin/pg_autoctl/pgctl.c
Labels: bug

#535 Review consequences of pg_autoctl set formation number-sync-standbys 0.
  src/bin/pg_autoctl/cli_enable_disable.c
  src/bin/pg_autoctl/fsm.c
  src/bin/pg_autoctl/monitor.c
  src/bin/pg_autoctl/monitor.h
  src/monitor/formation_metadata.c
  src/monitor/group_state_machine.c
  src/monitor/node_active_protocol.c
  src/monitor/node_metadata.c
  tests/pgautofailover_utils.py
  tests/test_enable_ssl.py
  tests/test_multi_ifdown.py
  tests/test_multi_maintenance.py
  tests/test_multi_standbys.py
Labels: Size:L, bug

#550 Fix bytes mangling opportunity.
  src/bin/lib/subcommands.c/runprogram.h
Labels: Size: S, bug

#549 pg autoctl show settings
  docs/architecture-multi-standby.rst
  docs/fsm.png
  docs/how-to.rst
  docs/ref/reference.rst
  src/bin/pg_autoctl/cli_common.h
  src/bin/pg_autoctl/cli_get_set_properties.c
  src/bin/pg_autoctl/cli_root.c
  src/bin/pg_autoctl/cli_show.c
Labels: Size: S, enhancement, user experience

#552 Refactor synchronous_standby_names checks in test suite.
  tests/pgautofailover_utils.py
  tests/test_basic_operation.py
  tests/test_multi_async.py
  tests/test_multi_ifdown.py
  tests/test_multi_maintenance.py
  tests/test_multi_standbys.py
Labels: Developer productivity, Size: S, enhancement

#556 Feature/docker run make cluster
  Dockerfile
  Makefile
  src/bin/pg_autoctl/cli_do_tmux.c
  src/bin/pg_autoctl/cli_do_tmux.h
  src/bin/pg_autoctl/pgctl.c
  src/bin/pg_autoctl/pgctl.h
Labels: Developer productivity, Size: S, user experience

#553 Test/run make installcheck in docker and travis
  Makefile
  src/monitor/expected/dummy_update.out
  src/monitor/expected/monitor.out
  src/monitor/expected/workers.out
  src/monitor/sql/monitor.sql
  src/monitor/sql/workers.sql
  tests/test_installcheck.py
Labels: Developer productivity, Size: S, enhancement

#560 Typo fix from a previous merge.
  Makefile
Labels: bug
