Repository hapostgres/pg_auto_failover, pull requests merged in 2020-04, with the labels that each got.

#221 Cleanup Makefile dependencies at `make clean` time.
  src/bin/pg_autoctl/Makefile
Labels: bug

#220 Speed up tests more by decreasing keeper sleep time
  src/bin/pg_autoctl/defaults.h
  tests/pgautofailover_utils.py
  tests/test_basic_operation.py
  tests/test_ensure.py
  tests/test_ssl_self_signed.py
Labels: enhancement

#224 Actually run the linting scripts we have in ci
  .gitattributes
  .travis.yml
  ci/banned.h.sh
  src/bin/pg_autoctl/cli_get_set_properties.c
  src/bin/pg_autoctl/cli_show.c
  src/bin/pg_autoctl/keeper_config.c
  src/bin/pg_autoctl/monitor.c
  src/bin/pg_autoctl/pgsql.c
Labels: enhancement

#212 Fix/systemd setup
  src/bin/pg_autoctl/cli_systemd.c
  src/bin/pg_autoctl/systemd_config.c
Labels: bug

#222 Feature/replication slots
  src/bin/pg_autoctl/fsm.c
  src/bin/pg_autoctl/fsm.h
  src/bin/pg_autoctl/fsm_transition.c
  src/bin/pg_autoctl/keeper.c
  src/bin/pg_autoctl/keeper.h
  src/bin/pg_autoctl/keeper_config.c
  src/bin/pg_autoctl/keeper_pg_init.c
  src/bin/pg_autoctl/pgctl.c
  src/bin/pg_autoctl/pgctl.h
  src/bin/pg_autoctl/pgsql.c
  src/bin/pg_autoctl/pgsql.h
  src/bin/pg_autoctl/primary_standby.c
  src/bin/pg_autoctl/primary_standby.h
  src/bin/pg_autoctl/string_utils.c
  src/monitor/node_metadata.c
  tests/pgautofailover_utils.py
  tests/test_auth.py
  tests/test_basic_operation.py
  tests/test_ensure.py
  tests/test_skip_pg_hba.py
  tests/test_ssl_cert.py
Labels: enhancement

#236 Return non-zero exit code when command parsing fails
  src/bin/lib/subcommands.c/commandline.c
  src/bin/lib/subcommands.c/commandline.h
  src/bin/pg_autoctl/main.c
Labels: user experience

#239 Fix problems with empty sslmode in show uri command
  src/bin/pg_autoctl/cli_show.c
  src/bin/pg_autoctl/keeper_config.c
  src/bin/pg_autoctl/pgsetup.c
Labels: bug

#240 Improve "show uri" command
  src/bin/pg_autoctl/cli_show.c
  src/bin/pg_autoctl/keeper_config.c
  src/bin/pg_autoctl/monitor_config.c
Labels: bug, user experience

#209 add missing errcode
  src/monitor/formation_metadata.c
  src/monitor/node_active_protocol.c
  src/monitor/node_metadata.c
Labels: enhancement

#245 Drop removed replication slots when disabling replication
  src/bin/pg_autoctl/fsm_transition.c
  src/bin/pg_autoctl/monitor_pg_init.c
  src/bin/pg_autoctl/primary_standby.c
  tests/pgautofailover_utils.py
Labels: bug

#247 Don't create pgautofailover_monitor user anymore
  src/bin/pg_autoctl/cli_do_misc.c
  src/bin/pg_autoctl/cli_do_root.c
  src/bin/pg_autoctl/cli_do_root.h
  src/bin/pg_autoctl/fsm_transition.c
  src/bin/pg_autoctl/primary_standby.c
  src/bin/pg_autoctl/primary_standby.h
  src/monitor/health_check_worker.c
  tests/test_auth.py
Labels: enhancement

#233 Implement a way to update to SSL when it's not been installed yet.
  docs/ref/reference.rst
  docs/security.rst
  src/bin/pg_autoctl/cli_common.c
  src/bin/pg_autoctl/cli_common.h
  src/bin/pg_autoctl/cli_config.c
  src/bin/pg_autoctl/cli_create_drop_node.c
  src/bin/pg_autoctl/cli_do_misc.c
  src/bin/pg_autoctl/cli_enable_disable.c
  src/bin/pg_autoctl/cli_service.c
  src/bin/pg_autoctl/config.c
  src/bin/pg_autoctl/config.h
  src/bin/pg_autoctl/fsm_transition.c
  src/bin/pg_autoctl/keeper.c
  src/bin/pg_autoctl/keeper.h
  src/bin/pg_autoctl/keeper_config.c
  src/bin/pg_autoctl/keeper_pg_init.c
  src/bin/pg_autoctl/keeper_pg_init.h
  src/bin/pg_autoctl/loop.c
  src/bin/pg_autoctl/monitor.c
  src/bin/pg_autoctl/monitor.h
  src/bin/pg_autoctl/monitor_config.c
  src/bin/pg_autoctl/monitor_config.h
  src/bin/pg_autoctl/monitor_pg_init.c
  src/bin/pg_autoctl/monitor_pg_init.h
  src/bin/pg_autoctl/monitor_service.c
  src/bin/pg_autoctl/monitor_service.h
  src/bin/pg_autoctl/parsing.c
  src/bin/pg_autoctl/parsing.h
  src/bin/pg_autoctl/pgctl.c
  src/bin/pg_autoctl/pgctl.h
  src/bin/pg_autoctl/pgsetup.c
  src/bin/pg_autoctl/pgsql.c
  src/bin/pg_autoctl/pgsql.h
  src/bin/pg_autoctl/primary_standby.c
  src/bin/pg_autoctl/primary_standby.h
  src/bin/pg_autoctl/service.c
  tests/pgautofailover_utils.py
  tests/test_enable_ssl.py
  tests/test_ssl_self_signed.py
Labels: docs
