Repository hapostgres/pg_auto_failover, pull requests merged in 2020-03, with the labels that each got.

#178 Error out when the pgautofailover is not in shared_preload_libraries.
  src/monitor/pg_auto_failover.c
Labels: bug

#173 Add .editorconfig so indentation is done right across editors
  .editorconfig
Labels: enhancement

#179 Implement pg_autoctl drop monitor and drop node --nodename --nodeport.
  docs/ref/reference.rst
  src/bin/pg_autoctl/cli_common.c
  src/bin/pg_autoctl/cli_common.h
  src/bin/pg_autoctl/cli_create_drop_node.c
  src/bin/pg_autoctl/cli_root.c
Labels: enhancement

#183 Fix issues found by static analysis
  src/bin/pg_autoctl/file_utils.c
  src/bin/pg_autoctl/file_utils.h
  src/bin/pg_autoctl/ini_file.c
  src/bin/pg_autoctl/ini_implementation.c
  src/bin/pg_autoctl/keeper_config.c
  src/bin/pg_autoctl/monitor.c
  src/bin/pg_autoctl/monitor_config.c
  src/bin/pg_autoctl/parsing.c
  src/bin/pg_autoctl/pgctl.c
  src/bin/pg_autoctl/pgsetup.c
  src/bin/pg_autoctl/state.c
  src/monitor/group_state_machine.c
  src/monitor/health_check_metadata.c
  src/monitor/node_active_protocol.c
  src/monitor/node_metadata.c
Labels: bug

#184 Second batch of static analysis fixes
  src/bin/pg_autoctl/cli_common.c
  src/bin/pg_autoctl/cli_config.c
  src/bin/pg_autoctl/cli_create_drop_node.c
  src/bin/pg_autoctl/cli_do_fsm.c
  src/bin/pg_autoctl/cli_service.c
  src/bin/pg_autoctl/cli_show.c
  src/bin/pg_autoctl/keeper_pg_init.c
  src/bin/pg_autoctl/monitor.c
  src/bin/pg_autoctl/pgsql.c
  src/bin/pg_autoctl/primary_standby.c
Labels: bug

#182 Use our own secure version of fprintf.
  src/bin/lib/README.md
  src/bin/lib/log/src/log.c
  src/bin/lib/pg/README.md
  src/bin/lib/pg/snprintf.c
  src/bin/lib/pg/snprintf.h
  src/bin/lib/pg/strerror.c
  src/bin/pg_autoctl/Makefile
  src/bin/pg_autoctl/cli_common.c
  src/bin/pg_autoctl/cli_common.h
  src/bin/pg_autoctl/cli_config.c
  src/bin/pg_autoctl/cli_do_fsm.c
  src/bin/pg_autoctl/cli_do_misc.c
  src/bin/pg_autoctl/cli_do_monitor.c
  src/bin/pg_autoctl/cli_do_show.c
  src/bin/pg_autoctl/cli_enable_disable.c
  src/bin/pg_autoctl/cli_root.c
  src/bin/pg_autoctl/cli_service.c
  src/bin/pg_autoctl/cli_show.c
  src/bin/pg_autoctl/config.c
  src/bin/pg_autoctl/debian.c
  src/bin/pg_autoctl/file_utils.c
  src/bin/pg_autoctl/file_utils.h
  src/bin/pg_autoctl/fsm.c
  src/bin/pg_autoctl/ini_file.c
  src/bin/pg_autoctl/ipaddr.c
  src/bin/pg_autoctl/keeper.c
  src/bin/pg_autoctl/keeper_config.c
  src/bin/pg_autoctl/loop.c
  src/bin/pg_autoctl/monitor.c
  src/bin/pg_autoctl/parsing.c
  src/bin/pg_autoctl/pgctl.c
  src/bin/pg_autoctl/pgsetup.c
  src/bin/pg_autoctl/state.c
Labels: bug

#186 Implement sformat, a secured version of snprintf.
  src/bin/pg_autoctl/file_utils.c
  src/bin/pg_autoctl/file_utils.h
  src/bin/pg_autoctl/fsm_transition.c
  src/bin/pg_autoctl/ini_file.c
  src/bin/pg_autoctl/ipaddr.c
  src/bin/pg_autoctl/keeper_config.c
  src/bin/pg_autoctl/keeper_pg_init.c
  src/bin/pg_autoctl/loop.c
  src/bin/pg_autoctl/monitor.c
  src/bin/pg_autoctl/monitor_config.c
  src/bin/pg_autoctl/parsing.c
  src/bin/pg_autoctl/parsing.h
  src/bin/pg_autoctl/pgctl.c
  src/bin/pg_autoctl/pghba.c
  src/bin/pg_autoctl/pgsetup.c
  src/bin/pg_autoctl/pgsql.c
  src/bin/pg_autoctl/pgsql.h
  src/bin/pg_autoctl/state.c
  src/bin/pg_autoctl/systemd_config.c
Labels: bug

#185 Replace getenv calls with safer ones
  ci/banned.h.sh
  src/bin/pg_autoctl/Makefile
  src/bin/pg_autoctl/cli_common.c
  src/bin/pg_autoctl/cli_create_drop_node.c
  src/bin/pg_autoctl/cli_enable_disable.c
  src/bin/pg_autoctl/cli_formation.c
  src/bin/pg_autoctl/cli_perform.c
  src/bin/pg_autoctl/cli_show.c
  src/bin/pg_autoctl/cli_systemd.c
  src/bin/pg_autoctl/config.c
  src/bin/pg_autoctl/defaults.h
  src/bin/pg_autoctl/env_utils.c
  src/bin/pg_autoctl/env_utils.h
  src/bin/pg_autoctl/file_utils.c
  src/bin/pg_autoctl/file_utils.h
  src/bin/pg_autoctl/fsm_transition.c
  src/bin/pg_autoctl/ipaddr.c
  src/bin/pg_autoctl/keeper_pg_init.c
  src/bin/pg_autoctl/main.c
  src/bin/pg_autoctl/monitor.c
  src/bin/pg_autoctl/pgctl.c
  src/bin/pg_autoctl/pgsetup.c
Labels: bug

#190 Open files in a safe way
  src/bin/pg_autoctl/debian.c
  src/bin/pg_autoctl/defaults.h
  src/bin/pg_autoctl/file_utils.c
  src/bin/pg_autoctl/file_utils.h
  src/bin/pg_autoctl/keeper_config.c
  src/bin/pg_autoctl/monitor_config.c
  src/bin/pg_autoctl/pgsetup.c
Labels: bug

#191 Replace some leftover strerror with %m
  src/bin/pg_autoctl/file_utils.c
  src/bin/pg_autoctl/pgsetup.c
Labels: bug

#192 Replace some leftover s(n)printfs
  src/bin/pg_autoctl/keeper.c
  src/monitor/health_check_worker.c
  src/monitor/pg_auto_failover.c
Labels: bug

#188 Remove most memcpy usages
  src/bin/pg_autoctl/cli_common.c
  src/bin/pg_autoctl/cli_create_drop_node.c
  src/bin/pg_autoctl/debian.c
  src/bin/pg_autoctl/keeper.c
  src/bin/pg_autoctl/keeper_config.c
  src/bin/pg_autoctl/monitor_config.c
  src/bin/pg_autoctl/state.c
  src/bin/pg_autoctl/state.h
Labels: bug

#189 Replace ctime with ctime_r
  src/bin/pg_autoctl/defaults.h
  src/bin/pg_autoctl/state.c
  src/bin/pg_autoctl/state.h
Labels: bug

#194 Fix warnings that GCC 7.4.0 throws
  .travis.yml
  src/bin/pg_autoctl/Makefile
  src/bin/pg_autoctl/cli_common.c
  src/bin/pg_autoctl/debian.c
  src/bin/pg_autoctl/pghba.c
  src/bin/pg_autoctl/pgsetup.c
  src/bin/pg_autoctl/pgsql.c
Labels: bug

#201 Improve docs related to SSL options
  docs/security.rst
  src/bin/pg_autoctl/cli_common.c
  src/bin/pg_autoctl/cli_common.h
  src/bin/pg_autoctl/cli_create_drop_node.c
  src/bin/pg_autoctl/fsm_transition.c
  src/bin/pg_autoctl/keeper_pg_init.c
  src/bin/pg_autoctl/pgsetup.c
  src/bin/pg_autoctl/primary_standby.c
Labels: bug, docs

#202 QA fixes.
  src/bin/pg_autoctl/pgsetup.c
  src/bin/pg_autoctl/primary_standby.c
Labels: bug

#204 Set citus.node_conninfo sslmode to --ssl-mode.
  src/bin/pg_autoctl/pgctl.c
  src/bin/pg_autoctl/primary_standby.c
Labels: bug
