Repository hapostgres/pg_auto_failover, pull requests merged in 2020-01, with the labels that each got.

#139 Fix/test suite
  Makefile
  tests/network.py
  tests/pgautofailover_utils.py
  tests/test_basic_operation.py
  tests/test_create_run.py
  tests/test_multi_standbys.py
Labels: bug

#138 Make destroy command public
  src/bin/pg_autoctl/cli_common.h
  src/bin/pg_autoctl/cli_create_drop_node.c
  src/bin/pg_autoctl/cli_do_misc.c
  src/bin/pg_autoctl/cli_do_root.c
  src/bin/pg_autoctl/cli_do_root.h
  src/bin/pg_autoctl/cli_root.c
  tests/pgautofailover_utils.py
Labels: enhancement

#142 Add some security details on db accessibility
  docs/operations.rst
Labels: docs

#140 Implement --json for (almost) all commands.
  src/bin/pg_autoctl/Makefile
  src/bin/pg_autoctl/cli_common.c
  src/bin/pg_autoctl/cli_common.h
  src/bin/pg_autoctl/cli_config.c
  src/bin/pg_autoctl/cli_do_fsm.c
  src/bin/pg_autoctl/cli_do_monitor.c
  src/bin/pg_autoctl/cli_enable_disable.c
  src/bin/pg_autoctl/cli_get_set_properties.c
  src/bin/pg_autoctl/cli_service.c
  src/bin/pg_autoctl/cli_show.c
  src/bin/pg_autoctl/ini_file.c
  src/bin/pg_autoctl/ini_file.h
  src/bin/pg_autoctl/keeper.c
  src/bin/pg_autoctl/keeper_config.c
  src/bin/pg_autoctl/keeper_config.h
  src/bin/pg_autoctl/monitor_config.c
  src/bin/pg_autoctl/monitor_config.h
  src/bin/pg_autoctl/pgsetup.c
  src/bin/pg_autoctl/pgsetup.h
  src/bin/pg_autoctl/state.c
  src/bin/pg_autoctl/state.h
Labels: enhancement

#134 Feature/multiple other node
  src/bin/pg_autoctl/cli_common.h
  src/bin/pg_autoctl/cli_do_fsm.c
  src/bin/pg_autoctl/cli_do_monitor.c
  src/bin/pg_autoctl/cli_root.c
  src/bin/pg_autoctl/cli_show.c
  src/bin/pg_autoctl/defaults.h
  src/bin/pg_autoctl/fsm.c
  src/bin/pg_autoctl/fsm_transition.c
  src/bin/pg_autoctl/keeper.c
  src/bin/pg_autoctl/keeper.h
  src/bin/pg_autoctl/keeper_config.c
  src/bin/pg_autoctl/keeper_config.h
  src/bin/pg_autoctl/monitor.c
  src/bin/pg_autoctl/monitor.h
  src/bin/pg_autoctl/pgsql.c
  src/bin/pg_autoctl/pgsql.h
  src/bin/pg_autoctl/primary_standby.c
  src/bin/pg_autoctl/state.c
  src/bin/pg_autoctl/state.h
  src/monitor/Makefile
  src/monitor/expected/dummy_update.out
  src/monitor/expected/monitor.out
  src/monitor/expected/upgrade.out
  src/monitor/group_state_machine.c
  src/monitor/node_active_protocol.c
  src/monitor/node_metadata.c
  src/monitor/node_metadata.h
  src/monitor/pgautofailover--1.0--1.1.sql
  src/monitor/pgautofailover.sql
  src/monitor/replication_state.c
  src/monitor/replication_state.h
  src/monitor/sql/upgrade.sql
  tests/test_basic_operation.py
Labels: enhancement

#147 Ensure current state before reaching the assigned state.
  src/bin/pg_autoctl/keeper.c
  src/bin/pg_autoctl/keeper.h
  src/bin/pg_autoctl/loop.c
  tests/pgautofailover_utils.py
  tests/test_ensure.py
Labels: bug

#146 Feature/set nodename
  src/bin/pg_autoctl/cli_enable_disable.c
  src/bin/pg_autoctl/cli_get_set_properties.c
  src/bin/pg_autoctl/defaults.h
  src/bin/pg_autoctl/fsm.c
  src/bin/pg_autoctl/fsm.h
  src/bin/pg_autoctl/fsm_transition.c
  src/bin/pg_autoctl/monitor.c
  src/bin/pg_autoctl/monitor.h
  src/bin/pg_autoctl/pgsql.c
  src/bin/pg_autoctl/pgsql.h
  src/bin/pg_autoctl/primary_standby.c
  src/bin/pg_autoctl/primary_standby.h
  src/bin/pg_autoctl/state.c
  src/bin/pg_autoctl/state.h
  src/monitor/formation_metadata.c
  src/monitor/formation_metadata.h
  src/monitor/group_state_machine.c
  src/monitor/node_active_protocol.c
  src/monitor/node_metadata.c
  src/monitor/node_metadata.h
  src/monitor/pgautofailover--1.0--1.1.sql
  src/monitor/pgautofailover.sql
  src/monitor/replication_state.c
  src/monitor/replication_state.h
  src/monitor/version_compat.c
  src/monitor/version_compat.h
  tests/pgautofailover_utils.py
  tests/test_multi_standbys.py
Labels: enhancement

#151 Refrain from setting pgSetup.pg_ctl for pg_autoctl show state|nodes.
  src/bin/pg_autoctl/cli_show.c
Labels: bug

#150 Fix a race condition at initialization time.
  src/monitor/expected/monitor.out
  src/monitor/node_active_protocol.c
  src/monitor/sql/monitor.sql
Labels: bug

#149 Fix/json
  src/bin/pg_autoctl/cli_do_monitor.c
  src/bin/pg_autoctl/cli_show.c
  src/bin/pg_autoctl/monitor.c
  src/bin/pg_autoctl/monitor.h
  src/monitor/node_active_protocol.c
Labels: bug, enhancement

#152 Stale postmaster pid
  src/bin/pg_autoctl/keeper.c
  src/bin/pg_autoctl/monitor.c
  src/bin/pg_autoctl/pgsetup.c
  src/bin/pg_autoctl/primary_standby.c
Labels: bug
