Repository hapostgres/pg_auto_failover, pull requests merged in 2020-10, with the labels that each got.

#444 Add documentation about how to run tests to CONTRIBUTING.md
  CONTRIBUTING.md
Labels: docs

#447 Docs/tikz color review
  docs/tikz/Makefile
  docs/tikz/arch-multi-standby.svg
  docs/tikz/arch-multi-standby.tex
  docs/tikz/arch-single-standby.svg
  docs/tikz/arch-single-standby.tex
  docs/tikz/arch-three-standby-one-async.svg
  docs/tikz/arch-three-standby-one-async.tex
  docs/tikz/arch-three-standby.svg
  docs/tikz/arch-three-standby.tex
  docs/tikz/common.tex
  docs/tikz/fsm.svg
  docs/tikz/fsm.tex
Labels: docs

#451 Force closing the connection used to check replication slots.
  src/bin/pg_autoctl/primary_standby.c
Labels: bug

#439 Fix when to ProceedWithMSFailover after a candidate is selected.
  src/monitor/group_state_machine.c
  src/monitor/node_metadata.c
  src/monitor/node_metadata.h
  tests/test_multi_async.py
Labels: bug

#455 Ensure that the monitor owns the Postgres (sub-)process.
  src/bin/pg_autoctl/defaults.h
  src/bin/pg_autoctl/pgsql.c
  src/bin/pg_autoctl/pgsql.h
  src/bin/pg_autoctl/primary_standby.c
  src/bin/pg_autoctl/primary_standby.h
  src/bin/pg_autoctl/service_monitor.c
  src/bin/pg_autoctl/service_postgres.c
  src/bin/pg_autoctl/service_postgres_ctl.c
  src/bin/pg_autoctl/state.c
  src/bin/pg_autoctl/state.h
  tests/test_basic_operation.py
Labels: bug

#458 Implement HBA hostname DNS checks, and warn users when needed.
  src/bin/pg_autoctl/cli_do_show.c
  src/bin/pg_autoctl/ipaddr.c
  src/bin/pg_autoctl/ipaddr.h
  src/bin/pg_autoctl/pghba.c
  src/bin/pg_autoctl/pghba.h
Labels: user experience

#459 Update documentation to use pg_auto_failover 1.4 with Postgres 12.
  docs/install.rst
Labels: bug, docs

#460 Avoid a race condition between file_exists() and read_file().
  src/bin/pg_autoctl/file_utils.c
  src/bin/pg_autoctl/file_utils.h
  src/bin/pg_autoctl/pgsetup.c
Labels: bug, user experience

#461 Refrain from using FIRST %d in synchronous_standby_names.
  src/monitor/node_active_protocol.c
  src/monitor/node_metadata.c
Labels: enhancement

#462 Always use node id and node name in messages.
  src/bin/pg_autoctl/cli_do_monitor.c
  src/bin/pg_autoctl/fsm_transition.c
  src/bin/pg_autoctl/monitor.c
  src/bin/pg_autoctl/pgctl.c
  src/bin/pg_autoctl/pghba.c
  src/bin/pg_autoctl/primary_standby.c
  src/monitor/formation_metadata.c
  src/monitor/group_state_machine.c
  src/monitor/node_active_protocol.c
  src/monitor/node_metadata.h
Labels: user experience

#478 Review memory/malloc errors and potential leaks.
  src/bin/pg_autoctl/cli_do_tmux.c
  src/bin/pg_autoctl/cli_show.c
  src/bin/pg_autoctl/defaults.h
  src/bin/pg_autoctl/file_utils.c
  src/bin/pg_autoctl/keeper.c
  src/bin/pg_autoctl/lock_utils.c
  src/bin/pg_autoctl/parsing.c
  src/bin/pg_autoctl/pgctl.c
  src/bin/pg_autoctl/pidfile.c
  src/bin/pg_autoctl/supervisor.c
Labels: bug

#475 Make it obvious when an extension is missing.
  src/bin/pg_autoctl/monitor.c
  src/bin/pg_autoctl/monitor_pg_init.c
Labels: user experience

#480 Review APPLY_SETTINGS transitions in cases including node removal.
  src/bin/pg_autoctl/fsm.c
  src/bin/pg_autoctl/fsm_transition.c
  src/monitor/node_active_protocol.c
  tests/pgautofailover_utils.py
  tests/test_multi_standbys.py
Labels: bug

#487 Add support for Citus worker specific transitions in IsBeingPromoted.
  src/monitor/node_metadata.c
Labels: bug
