Repository hapostgres/pg_auto_failover, pull requests merged in 2021-03, with the labels that each got.

#589 Fix supervisor messages about exited services.
  src/bin/pg_autoctl/supervisor.c
Labels: Developer productivity, Size: S, bug

#590 Fix memory management issue in monitor_register_node.
  src/bin/pg_autoctl/keeper.c
  src/bin/pg_autoctl/monitor.c
  src/bin/pg_autoctl/monitor.h
Labels: Size: S, bug

#601 Update README.md
  README.md
Labels: Size: S, docs, good first issue

#610 Fix a buffer overlap instruction that macOs libc fails to process.
  src/bin/pg_autoctl/keeper_pg_init.c
Labels: bug

#612 Add pg_logging_init for PG version 12 and above
  src/bin/pg_autoctl/main.c
Labels: bug

#609 Fix/skip hba propagation
  Makefile
  src/bin/pg_autoctl/cli_common.c
  src/bin/pg_autoctl/cli_do_root.c
  src/bin/pg_autoctl/cli_do_tmux.c
  src/bin/pg_autoctl/cli_do_tmux.h
  src/bin/pg_autoctl/keeper.c
  src/bin/pg_autoctl/keeper_config.c
  src/bin/pg_autoctl/pghba.c
  src/bin/pg_autoctl/pgsql.c
  tests/test_skip_pg_hba.py
Labels: bug

#615 Improve DNS lookup error handling.
  src/bin/pg_autoctl/cli_create_drop_node.c
  src/bin/pg_autoctl/cli_do_show.c
  src/bin/pg_autoctl/ipaddr.c
  src/bin/pg_autoctl/ipaddr.h
  src/bin/pg_autoctl/pghba.c
  src/bin/pg_autoctl/pghba.h
Labels: bug

#617 Review pg_autoctl show state output, and docs.
  docs/failover-state-machine.rst
  docs/fsm.png
  docs/tikz/fsm.svg
  docs/tikz/fsm.tex
  src/bin/pg_autoctl/nodestate_utils.c
  src/bin/pg_autoctl/nodestate_utils.h
Labels: Size: S, user experience

#629 Fix/synchronous standby name wildcard
  src/bin/pg_autoctl/cli_do_misc.c
  src/bin/pg_autoctl/cli_do_root.c
  src/bin/pg_autoctl/pgsql.c
  src/bin/pg_autoctl/pgsql.h
  src/bin/pg_autoctl/primary_standby.c
  src/bin/pg_autoctl/primary_standby.h
  src/monitor/node_active_protocol.c
  tests/test_auth.py
  tests/test_basic_operation.py
  tests/test_multi_maintenance.py
Labels: Size: S, bug

#623 Add support for systemd ExecReload option.
  src/bin/pg_autoctl/systemd_config.c
  src/bin/pg_autoctl/systemd_config.h
Labels: Size: S

#591 Implement online enable/disable monitor support.
  .travis.yml
  Makefile
  docs/conf.py
  docs/faq.rst
  docs/operations.rst
  docs/ref/reference.rst
  src/bin/pg_autoctl/cli_enable_disable.c
  src/bin/pg_autoctl/defaults.h
  src/bin/pg_autoctl/fsm.c
  src/bin/pg_autoctl/keeper.c
  src/bin/pg_autoctl/keeper.h
  src/bin/pg_autoctl/monitor.c
  src/bin/pg_autoctl/monitor.h
  src/bin/pg_autoctl/pgsql.c
  src/bin/pg_autoctl/state.c
  src/monitor/Makefile
  src/monitor/expected/dummy_update.out
  src/monitor/metadata.h
  src/monitor/node_active_protocol.c
  src/monitor/node_metadata.c
  src/monitor/node_metadata.h
  src/monitor/pgautofailover--1.5.0.1--1.5.0.2.sql
  src/monitor/pgautofailover--1.5.0.2--dummy.sql
  src/monitor/pgautofailover--1.5.0.2.sql
  src/monitor/pgautofailover.control
  src/monitor/pgautofailover.sql
  tests/pgautofailover_utils.py
  tests/test_replace_monitor.py
Labels: Size:M

#641 Fix links to our documentation.
  README.md
Labels: docs

#644 Prepare release 1.5.1.
  CHANGELOG.md
  Makefile
  docs/conf.py
  src/bin/pg_autoctl/azure.c
  src/bin/pg_autoctl/defaults.h
  src/monitor/Makefile
  src/monitor/expected/dummy_update.out
  src/monitor/metadata.h
  src/monitor/pgautofailover--1.4--1.5.sql
  src/monitor/pgautofailover--1.5--dummy.sql
  src/monitor/pgautofailover--1.5.0.1--1.5.0.2.sql
  src/monitor/pgautofailover--1.5.0.2.sql
  src/monitor/pgautofailover.control
Labels: release_checklist

#638 [WIP] Remove deprecated IPDB code from the tests.
  tests/Pipfile
  tests/Pipfile.lock
  tests/network.py
Labels: Developer productivity, Size:M

#652 Docs: typo fix for Postgres client certificate file (postgresql.crt).
  docs/security.rst
Labels: Size: S, docs

#582 Plug connection leaks found during profiling
  src/bin/pg_autoctl/cli_enable_disable.c
  src/bin/pg_autoctl/cli_get_set_properties.c
  src/bin/pg_autoctl/cli_perform.c
  src/bin/pg_autoctl/keeper.c
  src/bin/pg_autoctl/keeper_pg_init.c
  src/bin/pg_autoctl/monitor.c
  src/bin/pg_autoctl/monitor.h
  src/bin/pg_autoctl/monitor_pg_init.c
  src/bin/pg_autoctl/pgsql.c
  src/bin/pg_autoctl/pgsql.h
  src/bin/pg_autoctl/service_keeper.c
Labels: bug
