Repository hapostgres/pg_auto_failover, pull requests merged in 2021-12, with the labels that each got.

#842 Fix compat with Postgres 15devel again.
  src/bin/pg_autoctl/demoapp.c
  src/bin/pg_autoctl/pgsql.c
  src/bin/pg_autoctl/pgsql.h
Labels: bug

#845 Postgres 14 has been released and is fully supported now.
  .travis.yml
Labels: Size: S, Developer productivity, Packaging and CI

#846 Add support for more environment variables.
  src/bin/pg_autoctl/cli_common.c
  src/bin/pg_autoctl/defaults.h
  tests/test_auth.py
Labels: enhancement, Size: S

#848 Typo fix.
  src/bin/pg_autoctl/monitor.c
Labels: enhancement, docs, user experience, Size: S

#847 Fix a race condition in node registration.
  src/monitor/node_active_protocol.c
Labels: bug, user experience, Size: S

#849 Fix minor docs bug
  docs/operations.rst
Labels: docs

#855 Dx/fix dockerfile for pgversions
  Dockerfile
  Makefile
Labels: enhancement, Size: S, Developer productivity

#856 Correct typos in documentation and tests
  CHANGELOG.md
  README.md
  ci/banned.h.sh
  docs/how-to.rst
  docs/operations.rst
  docs/ref/pg_autoctl_config_check.rst
  docs/ref/pg_autoctl_config_get.rst
  docs/ref/pg_autoctl_config_set.rst
  docs/ref/pg_autoctl_create_postgres.rst
  docs/ref/pg_autoctl_get_formation_number_sync_standbys.rst
  docs/ref/pg_autoctl_get_formation_settings.rst
  docs/ref/pg_autoctl_get_node_candidate_priority.rst
  docs/ref/pg_autoctl_get_node_replication_quorum.rst
  docs/ref/pg_autoctl_set_formation_number_sync_standbys.rst
  docs/ref/pg_autoctl_set_node_candidate_priority.rst
  docs/ref/pg_autoctl_set_node_replication_quorum.rst
  docs/ref/pg_autoctl_show_events.rst
  docs/ref/pg_autoctl_show_file.rst
  docs/ref/pg_autoctl_show_settings.rst
  docs/ref/pg_autoctl_show_standby_names.rst
  docs/ref/pg_autoctl_show_state.rst
  docs/ref/pg_autoctl_show_uri.rst
  docs/ref/pg_autoctl_status.rst
  docs/security.rst
  src/bin/lib/README.md
  tests/network.py
  tests/pgautofailover_utils.py
  tests/test_multi_async.py
  tests/test_multi_standbys.py
Labels: enhancement, good first issue, docs, Size:M

#825 Implement make compose, using docker-compose for local interactive testing.
  .dockerignore
  .gitignore
  Dockerfile
  Makefile
  src/bin/pg_autoctl/cli_do_root.c
  src/bin/pg_autoctl/cli_do_root.h
  src/bin/pg_autoctl/cli_do_tmux.c
  src/bin/pg_autoctl/cli_do_tmux.h
  src/bin/pg_autoctl/cli_do_tmux_compose.c
Labels: Size:M, Developer productivity
