Repository hapostgres/pg_auto_failover, pull requests merged in 2021-08, with the labels that each got.

#772 Avoid re-electing primary during a switchover.
  Dockerfile
  Makefile
  src/monitor/group_state_machine.c
  src/monitor/node_active_protocol.c
  src/monitor/node_metadata.c
  tests/pgautofailover_utils.py
  tests/test_multi_standbys.py
Labels: Size: S, bug

#777 Bump theme version to fix docs search
  docs/requirements.txt
Labels: docs

#779 Improve error messages for missing configuration files.
  src/bin/pg_autoctl/debian.c
Labels: Size: S, bug

#781 Fix replication slot maintenance on secondary nodes.
  src/bin/pg_autoctl/pgsql.c
Labels: bug, Size: S

#771 Only exit at upgrade when the on-disk binary is ready.
  Dockerfile
  src/bin/pg_autoctl/cli_common.c
  src/bin/pg_autoctl/cli_do_demoapp.c
  src/bin/pg_autoctl/cli_do_show.c
  src/bin/pg_autoctl/ipaddr.c
  src/bin/pg_autoctl/keeper.c
  src/bin/pg_autoctl/keeper.h
  src/bin/pg_autoctl/keeper_pg_init.c
  src/bin/pg_autoctl/monitor_pg_init.c
  src/bin/pg_autoctl/pgsql.c
  tests/upgrade/Makefile
  tests/upgrade/README.md
  tests/upgrade/docker-compose.yml
  tests/upgrade/monitor-upgrade-1.7.patch
Labels: enhancement, Size: S
