Repository hapostgres/pg_auto_failover, pull requests merged in 2021-01, with the labels that each got.

#551 make NODES=3 NODES_ASYNC=2 NODES_PRIOS=50,0 NODES_SYNC_SB=0 cluster
  Makefile
  src/bin/pg_autoctl/cli_do_tmux.c
  src/bin/pg_autoctl/cli_do_tmux.h
Labels: Developer productivity, Size: S

#571 Fix tmux script when having PATH with spaces
  src/bin/pg_autoctl/cli_do_tmux.c
Labels: Developer productivity, bug

#570 Refrain from preventing changes that are not really changes.
  src/monitor/node_active_protocol.c
Labels: Size: S, bug

#561 Implement pg_autoctl create postgres --pg-hba-lan option.
  docker-compose.yml
  docs/ref/reference.rst
  src/bin/pg_autoctl/cli_common.c
  src/bin/pg_autoctl/cli_common.h
  src/bin/pg_autoctl/cli_create_drop_node.c
  src/bin/pg_autoctl/cli_do_misc.c
  src/bin/pg_autoctl/cli_do_root.c
  src/bin/pg_autoctl/cli_do_show.c
  src/bin/pg_autoctl/cli_do_tmux.c
  src/bin/pg_autoctl/defaults.h
  src/bin/pg_autoctl/fsm_transition.c
  src/bin/pg_autoctl/ipaddr.c
  src/bin/pg_autoctl/ipaddr.h
  src/bin/pg_autoctl/keeper.c
  src/bin/pg_autoctl/keeper_config.c
  src/bin/pg_autoctl/keeper_pg_init.c
  src/bin/pg_autoctl/monitor_config.c
  src/bin/pg_autoctl/monitor_pg_init.c
  src/bin/pg_autoctl/pghba.c
  src/bin/pg_autoctl/pghba.h
  src/bin/pg_autoctl/pgsetup.c
  src/bin/pg_autoctl/pgsetup.h
  src/bin/pg_autoctl/pgsql.c
  src/bin/pg_autoctl/primary_standby.c
  src/bin/pg_autoctl/primary_standby.h
Labels: Size: S, user experience

#572 Fix the return code when stop the node that is started by pg_autoctl
  src/bin/pg_autoctl/cli_service.c
Labels: bug
