Repository hapostgres/pg_auto_failover, pull requests merged in 2021-02, with the labels that each got.

#577 Set formation kind when expected.
  src/monitor/node_active_protocol.c
Labels: bug

#578 Fix retry loops with wait time to stop using 100% CPU.
  src/bin/pg_autoctl/service_postgres_ctl.c
Labels: Size: S, bug

#579 Prepare release 1.4.2.
  CHANGELOG.md
  Makefile
  docs/conf.py
  src/bin/lib/pg/strerror.c
  src/bin/pg_autoctl/azure.c
  src/bin/pg_autoctl/defaults.h
Labels: Size: S, release_checklist

#581 Plug few isolated memleaks that showed up during profiling
  src/bin/pg_autoctl/ipaddr.c
  src/bin/pg_autoctl/monitor.c
  src/bin/pg_autoctl/parsing.c
  src/bin/pg_autoctl/pgsetup.c
Labels: bug

#588 Refrain from reloading Postgres when we skip HBA editing anyways.
  src/bin/pg_autoctl/keeper.c
Labels: Size: S, bug

#568 Implement a demo application showing client-side HA with reconnections
  docker-compose.yml
  src/bin/pg_autoctl/cli_do_demoapp.c
  src/bin/pg_autoctl/cli_do_demoapp.h
  src/bin/pg_autoctl/cli_do_root.c
  src/bin/pg_autoctl/cli_do_root.h
  src/bin/pg_autoctl/demoapp.c
  src/bin/pg_autoctl/demoapp.h
  src/bin/pg_autoctl/pgsql.c
  src/bin/pg_autoctl/pgsql.h
Labels: Size:M

#576 Feature/zero config pg autoctl
  src/bin/pg_autoctl/cli_common.c
  src/bin/pg_autoctl/cli_common.h
  src/bin/pg_autoctl/cli_do_tmux.c
  src/bin/pg_autoctl/cli_do_tmux.h
  src/bin/pg_autoctl/cli_formation.c
  src/bin/pg_autoctl/cli_get_set_properties.c
  src/bin/pg_autoctl/cli_perform.c
  src/bin/pg_autoctl/cli_show.c
  src/bin/pg_autoctl/defaults.h
  src/bin/pg_autoctl/formation_config.h
  src/bin/pg_autoctl/parsing.c
  src/bin/pg_autoctl/parsing.h
  src/bin/pg_autoctl/pgsql.c
  src/monitor/node_active_protocol.c
  tests/pgautofailover_utils.py
Labels: Size:M, enhancement
