Repository hapostgres/pg_auto_failover, pull requests merged in 2021-11, with the labels that each got.

#828 Prepare/release 1.6.3
  .travis.yml
  CHANGELOG.md
  Makefile
  README.md
  docs/conf.py
  docs/ref/pg_autoctl_watch.rst
  src/bin/lib/pg/snprintf.c
  src/bin/lib/pg/strerror.c
  src/bin/pg_autoctl/azure.c
  src/bin/pg_autoctl/defaults.h
Labels: release_checklist

#830 Fix gcc-11 warnings that are popping-up when building on debian sid.
  src/bin/pg_autoctl/watch.c
Labels: bug, Size: S, Packaging and CI

#836 Handle return events for poll()
  src/monitor/health_check_worker.c
Labels: bug, user experience, Size: S, Developer productivity

#839 Bug/837 No need to checkpoint and restart if pg is not running
  src/bin/pg_autoctl/keeper.c
  tests/pgautofailover_utils.py
  tests/test_auth.py
Labels: bug, user experience

#838 Quick adjusting for Postgres 15devel compatibility.
  src/monitor/replication_state.c
  src/monitor/version_compat.h
Labels: enhancement, Size: S
