Repository hapostgres/pg_auto_failover, pull requests merged in 2021-05, with the labels that each got.

#693 Fix a memory leak in BuildNodesArrayValues.
  src/bin/pg_autoctl/pgsql.c
Labels: Size: S, bug

#691 make valgrind-session.
  Dockerfile
  Makefile
  valgrind/.gitignore
Labels: Developer productivity, Size: S

#697 Fix pg_autoctl show settings --json output.
  src/bin/pg_autoctl/monitor.c
Labels: Size: S, bug

#696 Fix an often failing test by improving the Group FSM robustness.
  src/monitor/group_state_machine.c
  src/monitor/node_metadata.c
Labels: Size: S, bug

#706 Complete transition of a second (or greater) failed primary
  Makefile
  src/monitor/node_metadata.c
  src/monitor/node_metadata.h
  tests/test_multi_alternate_primary_failures.py
Labels: Size:M, bug

#703 Log monitor health changes as events.
  src/monitor/health_check.h
  src/monitor/health_check_metadata.c
  src/monitor/health_check_worker.c
Labels: Size: S, enhancement

#695 Fix/consider timeline when reaching secondary
  Makefile
  src/bin/pg_autoctl/cli_do_misc.c
  src/bin/pg_autoctl/fsm.c
  src/bin/pg_autoctl/fsm.h
  src/bin/pg_autoctl/fsm_transition.c
  src/bin/pg_autoctl/pgctl.c
  src/bin/pg_autoctl/pgsetup.h
  src/bin/pg_autoctl/pgsql.c
  src/bin/pg_autoctl/pgsql.h
  src/bin/pg_autoctl/primary_standby.c
  src/bin/pg_autoctl/primary_standby.h
Labels: Size: S, bug

#656 Feature crash recovery before pg rewind
  src/bin/pg_autoctl/cli_do_misc.c
  src/bin/pg_autoctl/cli_do_root.c
  src/bin/pg_autoctl/cli_do_root.h
  src/bin/pg_autoctl/cli_service.c
  src/bin/pg_autoctl/parsing.c
  src/bin/pg_autoctl/pgctl.c
  src/bin/pg_autoctl/pgctl.h
  src/bin/pg_autoctl/pgsetup.c
  src/bin/pg_autoctl/pgsetup.h
  src/bin/pg_autoctl/pgsql.h
  src/bin/pg_autoctl/primary_standby.c
  src/bin/pg_autoctl/primary_standby.h
  src/bin/pg_autoctl/service_postgres.c
Labels: Size:M, enhancement, user experience

#711 Minor tweaks during the registration of healthcheck workers
  src/monitor/health_check_worker.c
Labels: Size:M, bug, enhancement
