Repository hapostgres/pg_auto_failover, pull requests merged in 2021-07, with the labels that each got.

#748 Have pg_autoctl drop node comment wait until the node has been removed.
  docs/ref/pg_autoctl_drop_node.rst
  src/bin/pg_autoctl/cli_drop_node.c
  src/bin/pg_autoctl/cli_enable_disable.c
  src/bin/pg_autoctl/monitor.c
  src/bin/pg_autoctl/monitor.h
Labels: Size: S, enhancement

#743 Have drop node --force --destroy work as expected again
  src/bin/pg_autoctl/cli_drop_node.c
  src/bin/pg_autoctl/pidfile.c
  src/bin/pg_autoctl/pidfile.h
  tests/pgautofailover_utils.py
Labels: Developer productivity, Size: S, enhancement

#751 Fix transaction begin failure handling
  src/bin/pg_autoctl/pgsql.c
Labels: Size: S, bug

#753 Add the reported timeline id to the monitor events table.
  src/bin/pg_autoctl/monitor.c
  src/monitor/notifications.c
  src/monitor/pgautofailover--1.5--1.6.sql
  src/monitor/pgautofailover.sql
  tests/pgautofailover_utils.py
Labels: Size: S, enhancement

#745 Desultory refactoring of the code.
  src/bin/pg_autoctl/cli_common.h
  src/bin/pg_autoctl/cli_do_monitor.c
  src/bin/pg_autoctl/cli_drop_node.c
  src/bin/pg_autoctl/fsm.c
  src/bin/pg_autoctl/fsm.h
  src/bin/pg_autoctl/fsm_transition.c
  src/bin/pg_autoctl/monitor.c
  src/bin/pg_autoctl/monitor.h
  src/bin/pg_autoctl/nodestate_utils.c
  src/bin/pg_autoctl/nodestate_utils.h
  src/bin/pg_autoctl/pgctl.c
  src/bin/pg_autoctl/primary_standby.c
  src/monitor/group_state_machine.c
  src/monitor/node_active_protocol.c
  src/monitor/pgautofailover--1.5--1.6.sql
  src/monitor/pgautofailover.sql
  tests/test_multi_async.py
Labels: Size:M

#755 Fix pgautofailover.update_secondary_check() for dropped nodes.
  src/monitor/pgautofailover--1.5--1.6.sql
  src/monitor/pgautofailover.sql
  tests/pgautofailover_utils.py
Labels: Size: S, bug

#756 Set candidate priority without waiting for state changes in more cases.
  src/bin/pg_autoctl/cli_get_set_properties.c
  src/bin/pg_autoctl/pgsql.c
Labels: Size: S, bug

#759 Fix a connection leak at SIGINT.
  src/bin/pg_autoctl/service_monitor.c
Labels: Size: S, bug

#757 Fix upgrades
  src/monitor/pgautofailover--1.5--1.6.sql
  src/monitor/pgautofailover.sql
Labels: Size: S, bug, release_checklist

#762 Release/1.6.1
  CHANGELOG.md
  Makefile
  docs/conf.py
  src/bin/lib/parson/parson.c
  src/bin/lib/parson/parson.h
  src/bin/lib/parson/tests/test_2.txt
  src/bin/lib/parson/tests/test_2_comments.txt
  src/bin/lib/parson/tests/test_2_pretty.txt
  src/bin/pg_autoctl/azure.c
  src/bin/pg_autoctl/defaults.h
Labels: release_checklist

#765 Use dynamic PQExpBuffer strings to build SQL queries.
  src/bin/pg_autoctl/pgsql.c
Labels: enhancement

#738 Use citus fork of theme for accessibility
  docs/_static/css/citus.css
  docs/conf.py
  docs/requirements.txt
Labels: docs
