Repository hapostgres/pg_auto_failover, pull requests merged in 2021-09, with the labels that each got.

#792 Fix problems with bad migration to 1.5
  src/monitor/pgautofailover--1.5--1.6.sql
Labels: bug

#789 Fix typo in docs for operations
  docs/operations.rst
Labels: docs, Size: S

#791 Fix typos
  docs/ref/pg_autoctl_show_file.rst
  src/bin/pg_autoctl/cli_common.c
  src/bin/pg_autoctl/cli_create_node.c
  src/bin/pg_autoctl/cli_do_tmux.c
  src/bin/pg_autoctl/cli_drop_node.c
  src/bin/pg_autoctl/cli_service.c
  src/bin/pg_autoctl/debian.c
  src/bin/pg_autoctl/file_utils.c
  src/bin/pg_autoctl/keeper.c
  src/bin/pg_autoctl/keeper_pg_init.c
  src/bin/pg_autoctl/lock_utils.c
  src/bin/pg_autoctl/pgctl.c
  src/bin/pg_autoctl/pgsetup.c
  src/bin/pg_autoctl/pgsql.c
  src/bin/pg_autoctl/primary_standby.c
  src/bin/pg_autoctl/service_monitor.c
  src/bin/pg_autoctl/state.c
  src/monitor/health_check_metadata.c
  src/monitor/node_active_protocol.c
  tests/pgautofailover_utils.py
Labels: enhancement, good first issue, Size: S

#790 Add docs for installing tex styles
  CONTRIBUTING.md
Labels: docs, Size: S

#793 Also retry libpq connections to a local host.
  src/bin/pg_autoctl/pgsql.c
Labels: enhancement, user experience, Size: S

#795 Increase allowed path env size
  src/bin/pg_autoctl/cli_do_tmux.c
Labels: Size: S, Developer productivity

#794 Only use wait_maintenance to wait for wait_primary
  src/bin/pg_autoctl/fsm.c
  src/monitor/group_state_machine.c
  src/monitor/node_active_protocol.c
  src/monitor/node_metadata.c
  src/monitor/node_metadata.h
Labels: enhancement, Size: S

#797 Use more cores while installing
  README.md
Labels: enhancement, Size: S, Developer productivity

#796 Get rid of the JOIN_PRIMARY state.
  docs/failover-state-machine.rst
  docs/tikz/arch-multi-standby.svg
  docs/tikz/fsm.svg
  docs/tikz/fsm.tex
  src/bin/pg_autoctl/cli_drop_node.c
  src/monitor/group_state_machine.c
  src/monitor/node_metadata.c
  tests/test_monitor_disabled.py
  tests/test_multi_standbys.py
Labels: enhancement, Size:M, Developer productivity

#799 Per valgrind, fix some memory leaks.
  src/bin/pg_autoctl/pgsql.c
  src/bin/pg_autoctl/service_keeper.c
Labels: bug, Size: S

#801 Make sure to disable sync rep when initializing a primary.
  src/bin/pg_autoctl/fsm_transition.c
Labels: bug, good first issue, user experience, Size: S

#802 When creating from an existing PGDATA, fix missing initialization.
  src/bin/pg_autoctl/keeper_pg_init.c
Labels: bug, Size: S

#804 Release/prepare 1.6.2
  CHANGELOG.md
  Makefile
  docs/conf.py
  src/bin/lib/parson/Makefile
  src/bin/lib/parson/parson.c
  src/bin/lib/parson/parson.h
  src/bin/lib/parson/tests.c
  src/bin/lib/parson/tests/test_2_serialized.txt
  src/bin/lib/parson/tests/test_2_serialized_pretty.txt
  src/bin/pg_autoctl/azure.c
  src/bin/pg_autoctl/defaults.h
  tests/upgrade/monitor-upgrade-1.7.patch
Labels: Size: S, release_checklist

#805 Fix typo in drop replication slot
  src/bin/pg_autoctl/cli_do_misc.c
Labels: docs, Size: S

#807 Not require primary node to be up for synchronous_standby_names
  src/monitor/node_active_protocol.c
Labels: bug, Size: S

#808 Remove Citus Bot token, we don't use it anymore.
  .travis.yml
Labels: Size: S, Developer productivity

#812 fix: Allow setting maximum-backup-rate on create postgres step
  docs/ref/pg_autoctl_create_postgres.rst
  src/bin/pg_autoctl/cli_common.c
  src/bin/pg_autoctl/cli_create_node.c
Labels: enhancement, good first issue, user experience, Size: S
