Repository hapostgres/pg_auto_failover, pull requests merged in 2021-04, with the labels that each got.

#659 Review find_extension_control_file() error handling.
  src/bin/pg_autoctl/keeper_pg_init.c
  src/bin/pg_autoctl/monitor.c
  src/bin/pg_autoctl/monitor_pg_init.c
  src/bin/pg_autoctl/pgctl.c
Labels: Size: S, bug

#658 Fix/identify system before pg basebackup
  src/bin/lib/subcommands.c/runprogram.h
  src/bin/pg_autoctl/primary_standby.c
Labels: Size: S, user experience

#671 Fix memory leak allocated by createPQExpBuffer()
  src/bin/pg_autoctl/cli_do_tmux_azure.c
  src/bin/pg_autoctl/pgctl.c
  src/bin/pg_autoctl/pghba.c
  src/bin/pg_autoctl/supervisor.c
Labels: bug

#666 Use PGDATA owner for the systemd service file.
  src/bin/pg_autoctl/cli_systemd.c
  src/bin/pg_autoctl/systemd_config.c
Labels: Size: S, bug

#665 Check that a "replication" connection is possible before pg_rewind.
  src/bin/pg_autoctl/fsm_transition.c
  src/bin/pg_autoctl/primary_standby.c
Labels: Size: S, enhancement

#664 Assorted tests improvements.
  Dockerfile
  tests/pgautofailover_utils.py
  tests/test_basic_operation.py
  tests/test_skip_pg_hba.py
Labels: Developer productivity, Size: S

#675 Review and finish the PR for scrubbing pg passwords in our logs.
  src/bin/pg_autoctl/cli_enable_disable.c
  src/bin/pg_autoctl/parsing.c
  src/bin/pg_autoctl/parsing.h
  src/bin/pg_autoctl/pgsql.c
Labels: Size: S, bug

#607 Replace enterprise commands with community
  docs/operations.rst
Labels: Size: S, docs

#661 Allow manual promotion of nodes with candidate priority zero.
  Dockerfile
  src/bin/pg_autoctl/cli_do_monitor.c
  src/bin/pg_autoctl/fsm.c
  src/bin/pg_autoctl/fsm.h
  src/bin/pg_autoctl/fsm_transition.c
  src/bin/pg_autoctl/keeper.c
  src/bin/pg_autoctl/keeper_pg_init.c
  src/bin/pg_autoctl/monitor.c
  src/bin/pg_autoctl/monitor.h
  src/bin/pg_autoctl/nodestate_utils.c
  src/bin/pg_autoctl/pgctl.c
  src/bin/pg_autoctl/pgsql.c
  src/bin/pg_autoctl/primary_standby.c
  src/bin/pg_autoctl/primary_standby.h
  src/bin/pg_autoctl/service_monitor.c
  src/monitor/group_state_machine.c
  src/monitor/node_active_protocol.c
  src/monitor/node_metadata.h
  tests/test_multi_ifdown.py
  tests/test_multi_standbys.py
Labels: Size:M, enhancement, user experience

#676 Fix parsing pg version string for replication slots support on standby.
  src/bin/pg_autoctl/cli_config.c
  src/bin/pg_autoctl/parsing.c
  src/bin/pg_autoctl/parsing.h
  src/bin/pg_autoctl/pgctl.c
  src/bin/pg_autoctl/pgsetup.c
Labels: Size: S, bug

#677 Implement a new configuration option listen_notifications_timeout.
  docs/ref/pg_autoctl_perform_failover.rst
  docs/ref/pg_autoctl_perform_promotion.rst
  src/bin/pg_autoctl/cli_perform.c
  src/bin/pg_autoctl/demoapp.c
  src/bin/pg_autoctl/keeper_config.c
  src/bin/pg_autoctl/keeper_config.h
  src/bin/pg_autoctl/monitor.c
  src/bin/pg_autoctl/monitor.h
Labels: Size: S, enhancement, user experience

#681 Fix/debian cluster for the monitor
  src/bin/pg_autoctl/cli_do_misc.c
  src/bin/pg_autoctl/debian.c
  src/bin/pg_autoctl/debian.h
  src/bin/pg_autoctl/keeper_pg_init.c
  src/bin/pg_autoctl/monitor_pg_init.c
  tests/pgautofailover_utils.py
  tests/test_debian_clusters.py
Labels: Size: S, bug, user experience

#686 Review some confusing SSL documentation.
  docs/security.rst
Labels: Size: S, bug

#687 Fix a memory leak in uri_contains_password.
  src/bin/pg_autoctl/cli_do_tmux.c
  src/bin/pg_autoctl/parsing.c
  src/bin/pg_autoctl/pgsetup.c
  src/bin/pg_autoctl/pgsql.c
Labels: Size: S, bug

#674 Improve docs color contrast for accessibility
  .readthedocs.yaml
  docs/_static/css/citus.css
  docs/_static/css/pygments.css
  docs/conf.py
  docs/requirements.txt
Labels: Size:M, docs

#688 Review and fix the initialize_program API.
  src/bin/lib/subcommands.c/runprogram.h
  src/bin/pg_autoctl/azure.c
  src/bin/pg_autoctl/cli_do_tmux.c
  src/bin/pg_autoctl/demoapp.c
  src/bin/pg_autoctl/pgctl.c
  src/bin/pg_autoctl/service_keeper.c
  src/bin/pg_autoctl/service_monitor.c
  src/bin/pg_autoctl/service_postgres_ctl.c
Labels: Size: S, bug
