Repository hapostgres/pg_auto_failover, pull requests merged in 2021-06, with the labels that each got.

#714 Install btree_gist when upgrade to >= 1.4, not just 1.4.
  src/bin/pg_autoctl/monitor.c
  src/bin/pg_autoctl/parsing.c
  src/bin/pg_autoctl/parsing.h
  tests/test_extension_update.py
Labels: Size: S, bug

#720 Fix a race condition issue around health check updates.
  src/monitor/health_check_metadata.c
Labels: Size: S, bug

#719 Keep the context around for as long as you need it
  src/monitor/health_check_worker.c
Labels: Size:M, bug

#722 An attempt to stabilize multi_async tests
  tests/test_multi_alternate_primary_failures.py
  tests/test_multi_async.py
  tests/test_multi_ifdown.py
  tests/test_multi_maintenance.py
Labels: Developer productivity, Size: S, bug

#699 Fix/pg autoctl drop node
  docs/ref/pg_autoctl_drop_node.rst
  src/bin/pg_autoctl/cli_common.c
  src/bin/pg_autoctl/cli_create_drop_node.c
  src/bin/pg_autoctl/cli_enable_disable.c
  src/bin/pg_autoctl/keeper.c
  src/bin/pg_autoctl/monitor.c
  src/bin/pg_autoctl/monitor.h
  src/bin/pg_autoctl/pgsql.c
  src/bin/pg_autoctl/pgsql.h
  src/monitor/node_active_protocol.c
Labels: Size: S, bug

#707 Fix how many nodes need to report their LSN to perform a failover.
  src/bin/pg_autoctl/fsm.c
  src/monitor/group_state_machine.c
  src/monitor/node_metadata.c
  tests/test_multi_alternate_primary_failures.py
  tests/test_multi_async.py
  tests/test_multi_maintenance.py
  tests/test_multi_standbys.py
Labels: Size: S, bug

#727 Allow an old primary node (demoted/catchingup) to join another election.
  src/bin/pg_autoctl/fsm_transition.c
  src/monitor/group_state_machine.c
  tests/test_multi_alternate_primary_failures.py
Labels: Size: S, bug

#716 Allow building pg_auto_failover with Postgres 14.
  .travis.yml
  Makefile
  src/bin/pg_autoctl/Makefile
  src/bin/pg_autoctl/cli_common.c
  src/bin/pg_autoctl/cli_do_tmux.c
  src/bin/pg_autoctl/parsing.c
  src/monitor/version_compat.h
Labels: Size: S, enhancement, good first issue

#729 Not all the monitor code got the memo about nodeid being a bigint.
  Dockerfile.i386
  Makefile
  src/bin/pg_autoctl/cli_do_misc.c
  src/bin/pg_autoctl/cli_do_monitor.c
  src/bin/pg_autoctl/cli_enable_disable.c
  src/bin/pg_autoctl/defaults.h
  src/bin/pg_autoctl/env_utils.c
  src/bin/pg_autoctl/file_utils.c
  src/bin/pg_autoctl/fsm_transition.c
  src/bin/pg_autoctl/keeper.c
  src/bin/pg_autoctl/keeper.h
  src/bin/pg_autoctl/keeper_config.c
  src/bin/pg_autoctl/keeper_config.h
  src/bin/pg_autoctl/keeper_pg_init.c
  src/bin/pg_autoctl/monitor.c
  src/bin/pg_autoctl/monitor.h
  src/bin/pg_autoctl/nodestate_utils.c
  src/bin/pg_autoctl/nodestate_utils.h
  src/bin/pg_autoctl/parsing.c
  src/bin/pg_autoctl/parsing.h
  src/bin/pg_autoctl/pgctl.c
  src/bin/pg_autoctl/pghba.c
  src/bin/pg_autoctl/pgsetup.c
  src/bin/pg_autoctl/pgsql.c
  src/bin/pg_autoctl/pgsql.h
  src/bin/pg_autoctl/pgtuning.c
  src/bin/pg_autoctl/primary_standby.c
  src/bin/pg_autoctl/state.h
  src/monitor/Makefile
  src/monitor/expected/dummy_update.out
  src/monitor/group_state_machine.h
  src/monitor/health_check.h
  src/monitor/health_check_metadata.c
  src/monitor/metadata.h
  src/monitor/node_active_protocol.c
  src/monitor/node_metadata.c
  src/monitor/node_metadata.h
  src/monitor/notifications.c
  src/monitor/pgautofailover--1.5--1.6.sql
  src/monitor/pgautofailover--1.6--dummy.sql
  src/monitor/pgautofailover.control
  src/monitor/pgautofailover.sql
Labels: Size:M, bug

#732 Pretty print kilobytes using kB instead of KB
  src/bin/pg_autoctl/system_utils.c
Labels: Size: S, bug

#731 Implement support for citus.local_hostname.
  src/bin/pg_autoctl/cli_do_misc.c
  src/bin/pg_autoctl/config.c
  src/bin/pg_autoctl/fsm_transition.c
  src/bin/pg_autoctl/ini_file.c
  src/bin/pg_autoctl/ini_file.h
  src/bin/pg_autoctl/keeper.c
  src/bin/pg_autoctl/keeper_pg_init.c
  src/bin/pg_autoctl/monitor_pg_init.c
  src/bin/pg_autoctl/pgctl.c
  src/bin/pg_autoctl/pgctl.h
  src/bin/pg_autoctl/primary_standby.c
  src/bin/pg_autoctl/primary_standby.h
Labels: Size: S, enhancement

#730 Track nodes current timeline on the monitor.
  src/bin/pg_autoctl/cli_do_monitor.c
  src/bin/pg_autoctl/cli_show.c
  src/bin/pg_autoctl/defaults.h
  src/bin/pg_autoctl/fsm.c
  src/bin/pg_autoctl/keeper.c
  src/bin/pg_autoctl/keeper_pg_init.c
  src/bin/pg_autoctl/monitor.c
  src/bin/pg_autoctl/monitor.h
  src/bin/pg_autoctl/nodestate_utils.c
  src/bin/pg_autoctl/nodestate_utils.h
  src/bin/pg_autoctl/parsing.c
  src/bin/pg_autoctl/pgsql.c
  src/bin/pg_autoctl/pgsql.h
  src/bin/pg_autoctl/service_keeper.c
  src/monitor/expected/monitor.out
  src/monitor/group_state_machine.c
  src/monitor/group_state_machine.h
  src/monitor/node_active_protocol.c
  src/monitor/node_metadata.c
  src/monitor/node_metadata.h
  src/monitor/pgautofailover--1.5--1.6.sql
  src/monitor/pgautofailover.sql
  src/monitor/sql/monitor.sql
Labels: Size: S, bug

#739 Fix Postgres 14 beta2 incompatibility.
  src/monitor/pg_auto_failover.c
Labels: Size: S, bug

#734 Implement drop-at-a-distance semantics.
  .travis.yml
  docs/conf.py
  docs/failover-state-machine.rst
  docs/fsm.png
  docs/ref/pg_autoctl_drop_node.rst
  src/bin/pg_autoctl/cli_common.c
  src/bin/pg_autoctl/cli_common.h
  src/bin/pg_autoctl/cli_create_node.c
  src/bin/pg_autoctl/cli_do_fsm.c
  src/bin/pg_autoctl/cli_do_monitor.c
  src/bin/pg_autoctl/cli_drop_node.c
  src/bin/pg_autoctl/cli_enable_disable.c
  src/bin/pg_autoctl/defaults.h
  src/bin/pg_autoctl/fsm.c
  src/bin/pg_autoctl/fsm.h
  src/bin/pg_autoctl/fsm_transition.c
  src/bin/pg_autoctl/keeper.c
  src/bin/pg_autoctl/keeper.h
  src/bin/pg_autoctl/keeper_pg_init.c
  src/bin/pg_autoctl/monitor.c
  src/bin/pg_autoctl/monitor.h
  src/bin/pg_autoctl/nodestate_utils.c
  src/bin/pg_autoctl/pgsql.c
  src/bin/pg_autoctl/pidfile.c
  src/bin/pg_autoctl/pidfile.h
  src/bin/pg_autoctl/service_keeper.c
  src/bin/pg_autoctl/service_postgres_ctl.c
  src/bin/pg_autoctl/state.c
  src/bin/pg_autoctl/state.h
  src/bin/pg_autoctl/supervisor.c
  src/bin/pg_autoctl/supervisor.h
  src/monitor/expected/monitor.out
  src/monitor/group_state_machine.c
  src/monitor/node_active_protocol.c
  src/monitor/node_metadata.c
  src/monitor/node_metadata.h
  src/monitor/pgautofailover--1.5--1.6.sql
  src/monitor/pgautofailover.sql
  src/monitor/replication_state.c
  src/monitor/replication_state.h
  src/monitor/sql/monitor.sql
  tests/pgautofailover_utils.py
Labels: Size: XL, enhancement, user experience

#740 Introduce hooks to implement refreshing the otherNodes array.
  src/bin/pg_autoctl/keeper.c
  src/bin/pg_autoctl/keeper.h
  src/bin/pg_autoctl/service_keeper.c
Labels: Size: S, enhancement

#733 Use sysctl(3) on BSD
  src/bin/pg_autoctl/system_utils.c
Labels: Size: S, enhancement, good first issue

#744 Review and update docs with the recent PRs.
  docs/operations.rst
  docs/ref/pg_autoctl_config_set.rst
  docs/ref/pg_autoctl_show_state.rst
Labels: Size: S, docs
