Repository hapostgres/pg_auto_failover, pull requests merged in 2022-01, with the labels that each got.

#862 Check return value of strdup calls
  src/bin/pg_autoctl/debian.c
  src/bin/pg_autoctl/ini_file.c
  src/bin/pg_autoctl/pgsql.c
Labels: bug, enhancement

#861 update theme version
  docs/_static/css/citus.css
  docs/requirements.txt
Labels: docs

#871 Minor: Remove duplication add error handling
  docker-compose.yml
  src/bin/pg_autoctl/pgctl.c
Labels: enhancement, Size: S, Developer productivity
