Repository hapostgres/pg_auto_failover, pull requests merged in 2022-05, with the labels that each got.

#893 Fix ssl test by ensuring the symlink is owned by root.
  tests/test_enable_ssl.py
  tests/test_ssl_cert.py
Labels: Size: S, Developer productivity

#894 Use DEBIAN_FRONTEND noninteractive in our Dockerfile.
  Dockerfile
  tests/tablespaces/Makefile
Labels: Size: S, Developer productivity, Packaging and CI

#895 Trigger github action workflow on pull requests to master.
  .github/workflows/build-package.yml
Labels: Size: S, Developer productivity, Packaging and CI

#884 Fix incorrect indentation of foreach block
  src/monitor/version_compat.c
Labels: Developer productivity

#886 Remove dead code
  src/bin/pg_autoctl/monitor.c
Labels: Developer productivity

#889 Fix potential out of bounds array access
  src/bin/pg_autoctl/watch_colspecs.h
Labels: bug, Developer productivity

#888 Fix check for negative pid
  src/bin/pg_autoctl/pidfile.c
Labels: bug

#887 Fix incorrect order of arguments in prototype
  src/bin/pg_autoctl/pgctl.h
Labels: bug

#899 Remove dead code
  src/bin/pg_autoctl/cli_do_azure.c
Labels: Developer productivity

#898 Avoid NULL pointer check
  src/monitor/node_active_protocol.c
Labels: Developer productivity

#901 Fix build on FreeBSD (sempahore union support).
  src/bin/pg_autoctl/Makefile
Labels: bug, Packaging and CI

#902 Review fixes for non-interactive Dockerfile builds.
  Dockerfile
Labels: Developer productivity, Packaging and CI
