Repository hapostgres/pg_auto_failover, pull requests merged in 2025-04, with the labels that each got.

#1077 Fix make compose
  Dockerfile
  Makefile
  Makefile.citus
  src/bin/pg_autoctl/cli_do_tmux_compose.c
Labels: bug, Developer productivity

#1069 Prepare for release 2.2
  CHANGELOG.md
  docs/conf.py
  src/bin/pg_autoctl/azure.c
  src/bin/pg_autoctl/defaults.h
  src/monitor/Makefile
  src/monitor/expected/dummy_update.out
  src/monitor/metadata.h
  src/monitor/pgautofailover--2.0--2.1.sql
  src/monitor/pgautofailover--2.1--2.2.sql
  src/monitor/pgautofailover--2.2--dummy.sql
  src/monitor/pgautofailover.control
Labels: Packaging and CI, release_checklist

#1081 Fix broken and obsolete repository URLs
  docs/citus-quickstart.rst
  docs/faq.rst
  docs/index.rst
  docs/tutorial.rst
  src/bin/pg_autoctl/keeper.c
  src/bin/pg_autoctl/pgsetup.c
Labels: docs
