Repository hapostgres/pg_auto_failover, pull requests merged in 2025-02, with the labels that each got.

#1061 Add support for PostgreSQL 17
  .github/workflows/run-tests.yml
  Makefile
  README.md
  docs/azure-tutorial.rst
  docs/install.rst
  src/bin/pg_autoctl/azure.c
  src/bin/pg_autoctl/cli_common.c
  src/bin/pg_autoctl/pgctl.c
  src/monitor/version_compat.h
Labels: enhancement, good first issue, Packaging and CI

#1039 Update Dockerfile to address warnings
  Dockerfile
Labels: good first issue, Packaging and CI

#1066 Drop i386 support
  Dockerfile.i386
  Makefile
Labels: good first issue, Developer productivity, Packaging and CI
